[project]
dependencies = [
    "customtkinter>=5.2.2",
    "requests>=2.32.3",
]
name = "converter"
version = "1.0.0"
description = "Currency exchange rate calculator"
readme = "README.md"
requires-python = ">=3.13"
